### ISSUE TITLE
Changer texte dans test.txt

### ISSUE THREAD

**Issue by dwaps** [dwaps-formation/test#2]
Il faudrait mettre Salut les coco à la place

**Comment by mirrrael** [comment]
Ok je la prends !

**Comment by dwaps** [comment]
Ok @mirrrael  je te mets dessus.

**Comment by dwaps** [comment]
![dwaps-50](https://user-images.githubusercontent.com/9659087/31561019-d8d44cb6-b056-11e7-826e-9cfc21e467e7.png)
